export const emotionOptions = [
  { value: "joy", label: "Радість / Joy" },
  { value: "sadness", label: "Смуток / Sadness" },
  { value: "anger", label: "Злість / Anger" },
  { value: "surprise", label: "Подив / Surprise" },
  { value: "calm", label: "Спокій / Calm" },
  { value: "fear", label: "Страх / Fear" },
  { value: "disgust", label: "Огида / Disgust" },
  { value: "love", label: "Любов / Love" },
  { value: "gratitude", label: "Вдячність / Gratitude" },
  { value: "anxiety", label: "Тривога / Anxiety" },
  { value: "confusion", label: "Розгубленість / Confusion" },
  { value: "hope", label: "Надія / Hope" },
  { value: "pride", label: "Гордість / Pride" },
  { value: "shame", label: "Сором / Shame" },
  { value: "embarrassment", label: "Ніяковість / Embarrassment" },
  { value: "loneliness", label: "Самотність / Loneliness" },
  { value: "relief", label: "Полегшення / Relief" },
  { value: "excitement", label: "Захоплення / Excitement" },
  { value: "boredom", label: "Нудьга / Boredom" },
  { value: "confidence", label: "Впевненість / Confidence" },
];
